version: '3'

services:

  # php_my_admin:
  #   build: ${src_build_phpmyadmin}
  #   container_name: phpmyadmin-pli
  #   environment:
  #     PMA_HOST: ${db_host_name}
  #     MYSQL_ROOT_PASSWORD: ${db_root_password}
  #     MYSQL_USER: ${db_user}
  #     MYSQL_PASSWORD: ${db_password}
  #   ports:
  #     - "8001:80"
  #   links:
  #     - db:db
    
  # db:
  #   build: ${src_build_db}
  #   container_name: mariadb-pli
  #   volumes:
  #     - ${src_volume_db}
  #   environment:
  #     MYSQL_DATABASE: PLI_db
  #     MYSQL_ROOT_PASSWORD: ${db_root_password}
  #     MYSQL_USER: ${db_user}
  #     MYSQL_PASSWORD: ${db_password}
  #     MYSQL_TCP_PORT: ${db_port}
  #   ports:
  #     - '3306:3306'

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PLI_db
    ports: 
        - 3307:3306
    # volumes:
    #   - ./api/db-data/database.sql:/docker-entrypoint-initdb.d/database.sql

  pli_back:
    build: ./PLI_Back
    container_name: pli_back
    volumes:
      - ./PLI_Back:/Desktop/
    # command: bash -c "python3 mysite/manage.py makemigrations && python3 mysite/manage.py migrate && python3 main_copy.py && python mysite/manage.py runserver 0.0.0.0:8000"
    command: python3 mysite/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    links:
      - db
    ports:
      - '8000:8000'

  # pli_front:
  #   build: ./pli-front
  #   container_name: pli_front
  #   volumes:
  #     - ./pli-front:/Desktop
  #   # command: bash -c "npm install && npm start"
  #   #command: bash -c "yarn start"
  #   links:
  #     - pli_back
  #   ports:
  #     - '3000:3000'
  #   command: npm start