# Generated by Django 3.2.8 on 2021-12-08 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_response_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('score', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user_badge', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
