# Generated by Django 3.2.8 on 2022-02-09 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.response'),
        ),
    ]
