FROM node:16.13.2-alpine
# Add a work directory
WORKDIR /Desktop
ENV PATH="./node_modules/.bin:$PATH"
# RUN apt-get update                          \
# && apt-get upgrade                          \
# && apt-get install curl                     \
# Copy app files
COPY . .
