import React from "react";
import Video from "./Video";
import "../styles/VideoReel.css";

function VideoReel() {
    return (
      <div className="videoReel">
        <a
          href="https://www.youtube.com/watch?v=w7ejDZ8SWv8"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="https://fr.reactjs.org/logo-og.png"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="ReactJS"
          />
        </a>
        <a
          href="https://www.youtube.com/watch?v=ENrzD9HAZK4"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="https://www.genious.blog/wp-content/uploads/2021/04/share-nodejs-logo.png?x46544"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="NodeJS"
          />
        </a>
        <a
          href="https://www.youtube.com/watch?v=w7ejDZ8SWv8"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="http://edsellandicho.com/tutorials/images/angularjs/angularjs-logo.png"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="AngularJS"
          />
        </a>
        <a
          href="https://www.youtube.com/watch?v=w7ejDZ8SWv8"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="https://www.synolia.com/wp-content/uploads/2019/12/header-vue-js.jpg"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="VueJS"
          />
        </a>
        <a
          href="https://www.youtube.com/watch?v=w7ejDZ8SWv8"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="https://play-lh.googleusercontent.com/85WnuKkqDY4gf6tndeL4_Ng5vgRk7PTfmpI4vHMIosyq6XQ7ZGDXNtYG2s0b09kJMw"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="HTML"
          />
        </a>
        <a
          href="https://www.youtube.com/watch?v=w7ejDZ8SWv8"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="https://cdn-icons-png.flaticon.com/512/919/919826.png"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="CSS"
          />
        </a>
        <a
          href="https://www.youtube.com/watch?v=w7ejDZ8SWv8"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="https://besthqwallpapers.com/Uploads/30-1-2020/120244/thumb2-python-logo-white-silk-texture-python-emblem-programming-language-python.jpg"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="Python"
          />
        </a>
        <a
          href="https://www.youtube.com/watch?v=w7ejDZ8SWv8"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="https://img.stackshare.io/service/994/4aGjtNQv.png"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="Django"
          />
        </a>
        <a
          href="https://www.youtube.com/watch?v=w7ejDZ8SWv8"
          target="_blank"
          rel="noreferrer"
        >
          <Video
            image="https://cdn.my-mooc.com/media/cache/catalog_product_458x275/mooc/logo/7da50319266cb91250ca93e25bb1c421df292028.png"
            profileSrc="https://pbs.twimg.com/profile_images/806970003941527552/sF8UtACd_400x400.jpg"
            title="Swift"
          />
        </a>
      </div>
    );
}

export default VideoReel;
